name: Bump xxx-flake version

on:
  push:
    tags:
      - "v*.*.*"

env:
  GIT_AUTHOR_NAME: ${{ github.repository_owner }}
  GIT_AUTHOR_EMAIL: ${{ github.repository_owner }}@users.noreply.github.com

jobs:
  bump-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Get the release version from the tag and old version
        shell: bash
        if: env.XXX_VERSION == ''
        run: |
          echo "XXX_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.XXX_VERSION }}"

      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1

      - name: Create update branch
        run: |
          git checkout -b auto-update/xxx-flake

      - name: Update version in flake.nix and get old version
        run: |
          echo "OLD_VERSION=${grep -owE 'v[0-9]+\.[0-9]+\.[0-9]+' flake.nix}" >> $GITHUB_ENV
          awk {sub(/v[0-9]+\.[0-9]+\.[0-9]+/, ${{ env.XXX_VERSION }}); print} flake.nix > flake.nix

      - name: Commit changes
        run: |
          git add .
          git commit -m 'xxx-flake updated'
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'xxx-flake: ${{ env.OLD_VERSION }} -> ${{ env.XXX_VERSION }}'
          branch: auto-update/xxx-flake
